// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1OrkJv1rDddAUbyvYG19btxyGbPEkLAc',
    appId: '1:48898175851:web:9a8983f3b2398ae375d22e',
    messagingSenderId: '48898175851',
    projectId: 'genie-bbbb5',
    authDomain: 'genie-bbbb5.firebaseapp.com',
    databaseURL: 'https://genie-bbbb5-default-rtdb.firebaseio.com',
    storageBucket: 'genie-bbbb5.appspot.com',
    measurementId: 'G-BT4F0ZQ8DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJBYv0Ui0d8nT-m1NzOsmfsfscd5KnCs8',
    appId: '1:48898175851:android:668093ea440891e775d22e',
    messagingSenderId: '48898175851',
    projectId: 'genie-bbbb5',
    databaseURL: 'https://genie-bbbb5-default-rtdb.firebaseio.com',
    storageBucket: 'genie-bbbb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAGsEXNDEfWLisX4eE5nyGzEPEAfaTbAg',
    appId: '1:48898175851:ios:34af7dbb9611024e75d22e',
    messagingSenderId: '48898175851',
    projectId: 'genie-bbbb5',
    databaseURL: 'https://genie-bbbb5-default-rtdb.firebaseio.com',
    storageBucket: 'genie-bbbb5.appspot.com',
    androidClientId: '48898175851-9kioqqsmfg90ss464hhkcj258rgemvqf.apps.googleusercontent.com',
    iosClientId: '48898175851-17e7r59hiuscs1p902cctg1gcgbu92j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.genie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAGsEXNDEfWLisX4eE5nyGzEPEAfaTbAg',
    appId: '1:48898175851:ios:34af7dbb9611024e75d22e',
    messagingSenderId: '48898175851',
    projectId: 'genie-bbbb5',
    databaseURL: 'https://genie-bbbb5-default-rtdb.firebaseio.com',
    storageBucket: 'genie-bbbb5.appspot.com',
    androidClientId: '48898175851-9kioqqsmfg90ss464hhkcj258rgemvqf.apps.googleusercontent.com',
    iosClientId: '48898175851-17e7r59hiuscs1p902cctg1gcgbu92j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.genie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1OrkJv1rDddAUbyvYG19btxyGbPEkLAc',
    appId: '1:48898175851:web:552eb1b446693e5375d22e',
    messagingSenderId: '48898175851',
    projectId: 'genie-bbbb5',
    authDomain: 'genie-bbbb5.firebaseapp.com',
    databaseURL: 'https://genie-bbbb5-default-rtdb.firebaseio.com',
    storageBucket: 'genie-bbbb5.appspot.com',
    measurementId: 'G-0F4M6LH5GM',
  );

}